Создайте двумерный массив 10x3, заполненный случайными значениями. В каждой строке выберите значение, наиболее близкое к 0.5.

In [5]:
import numpy as np

a =np.random.random((10,3)) -0.5

print(a+0.5)

print(np.min(abs(a)+0.5, axis = 1))

[[0.60097342 0.07722975 0.43448483]
 [0.72977581 0.11437795 0.40962209]
 [0.55336868 0.41345755 0.6693205 ]
 [0.94341996 0.64762218 0.15730042]
 [0.94195444 0.8770205  0.84521366]
 [0.10037082 0.15807788 0.78445018]
 [0.19408555 0.39101196 0.11613943]
 [0.91659339 0.50414051 0.71729167]
 [0.75364175 0.42503816 0.8550114 ]
 [0.48110553 0.34102096 0.18179139]]
[0.56551517 0.59037791 0.55336868 0.64762218 0.84521366 0.78445018
 0.60898804 0.50414051 0.57496184 0.51889447]


Создайте двумерный массив 6x6, заполненный случайными значениями. Затем сумму по каждой строке поделите на минимальный элемент из столбца с тем же индексом.

In [6]:
import numpy as np
s=0 
min=0
a=np.random.random((6, 6))
print(a)

for j in range(6):
    s=0 
    min=a[0][j]
    for i in range (6):
        if a[i][j]<min: 
             min=a[i][j]   
    s=(np.sum(a[j]))/min
    print(s)

[[0.9708135  0.24246105 0.05323515 0.3135824  0.14304739 0.75393007]
 [0.89440505 0.41534738 0.05736012 0.98188379 0.24785252 0.68327257]
 [0.60053248 0.7888384  0.93825846 0.22535994 0.15047779 0.56895055]
 [0.60783206 0.60190027 0.68235709 0.02980869 0.36889599 0.3128527 ]
 [0.66447584 0.13341134 0.27319702 0.65544898 0.29586189 0.51764499]
 [0.02844022 0.22551445 0.75259121 0.3807282  0.52984531 0.95019614]]
87.0974220974963
24.58652641500468
61.470999992765
87.34522148657473
17.756633545408455
9.16506568226808


На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

In [7]:
import numpy as np
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
max=0;
for i in range(8):
    
        if x[i+1]>max and x[i]==0 : 
             max=x[i+1]   
print(max)

5


Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.


In [8]:
import numpy as np
j=0
x = np.ones(10) 
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for j in i:
    x[j]+=1   
print(x)    

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]
