Создайте двумерный массив 10x3, заполненный случайными значениями. В каждой строке выберите значение, наиболее близкое к 0.5.

In [2]:
import numpy as np

a =np.random.random((10,3)) -0.5

print(a+0.5)

print(np.min(abs(a)+0.5, axis = 1))

[[0.77819006 0.77736233 0.67021346]
 [0.08753024 0.20723565 0.53217627]
 [0.46140981 0.05829594 0.92526372]
 [0.56099648 0.41811539 0.07780649]
 [0.27068766 0.47827519 0.41420669]
 [0.97890029 0.68139951 0.93936247]
 [0.27493418 0.4318381  0.35665452]
 [0.41349446 0.70600236 0.11674727]
 [0.11025904 0.1690071  0.52723442]
 [0.89625317 0.66257597 0.73649917]]
[0.67021346 0.53217627 0.53859019 0.56099648 0.52172481 0.68139951
 0.5681619  0.58650554 0.52723442 0.66257597]


Создайте двумерный массив 6x6, заполненный случайными значениями. Затем сумму по каждой строке поделите на минимальный элемент из столбца с тем же индексом.

In [3]:
import numpy as np
s=0 
min=0
a=np.random.random((6, 6))
print(a)

for j in range(6):
    s=0 
    min=a[0][j]
    for i in range (6):
        if a[i][j]<min: 
             min=a[i][j]   
    s=(np.sum(a[j]))/min
    print(s)

[[0.77481237 0.61213917 0.56083569 0.04972033 0.63310529 0.51993419]
 [0.22573002 0.77747212 0.89172292 0.83857935 0.78138055 0.79739219]
 [0.88161635 0.4751209  0.65973972 0.77575596 0.18376917 0.15776025]
 [0.16449567 0.76110267 0.84738786 0.26203135 0.02398534 0.23384997]
 [0.79128548 0.65060611 0.12112573 0.69926542 0.43993594 0.33422955]
 [0.63746467 0.15682649 0.62814449 0.33206138 0.21434566 0.71172172]]
19.15276585682002
27.497122976065555
25.87197912289928
46.11500132964772
126.5960183184989
16.991380243062476


На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

In [4]:
import numpy as np
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
max=0;
for i in range(8):
    
        if x[i+1]>max and x[i]==0 : 
             max=x[i+1]   
print(max)

5


Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.


In [6]:
import numpy as np
j=0
x = np.ones(10) 
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for j in i:
    x[j]+=1   
print(x)    

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


Написать функцию, реализующую алгоритм k-means. Входные и выходные значения функции должны быть аналогичны https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.cluster.vq.kmeans.html. Функция должна содержать только один цикл while (for).

In [7]:
a=np.arange(16).reshape(4,4)
d=[a[::-1,:].diagonal(i) for i in range(-a.shape[0]+1,a.shape[1])]
d = {b:d[b] for b in range(7)}
print(d)

{0: array([0]), 1: array([4, 1]), 2: array([8, 5, 2]), 3: array([12,  9,  6,  3]), 4: array([13, 10,  7]), 5: array([14, 11]), 6: array([15])}


С помощью реализованной функции kmeans выделить кластеры клиентов в разрезах возраст-доход, возрвст-покупательский индекс, доход-покупательский индекс. В каждом случае использовать elbow method для определения оптимального числа кластеров. Визуализировать полученные кластеры (каждый кластер изобразить собственным цветом). Дать интерпретацию полученным кластерам.